---
- hosts: dev
  remote_user: root
  roles:
    - role: cerebro
  vars:
    cerebro_version: 0.8.3
    cerebro_force_reinstall: false
    cerebro_home_dir: /opt/cerebro
    cerebro_host: "0.0.0.0"
    cerebro_port: 7000
    cerebro_service_enabled: true
    cerebro_service_state: started