---
- hosts: dev
  remote_user: root
  roles:
    - role: elastic.elasticsearch
  vars:
    es_heap_size: "1g"
    es_data_dirs:
      - "/data/es"
    es_config:
      cluster.name: "aza"
      cluster.initial_master_nodes: "192.168.56.101"
      discovery.seed_hosts: "192.168.56.101"
      http.port: 9200
      node.data: true
      bootstrap.memory_lock: false
 
